services:
  app-release-watcher:
    image: rajnishdock/app-release-watcher:latest
    container_name: app-release-watcher
    restart: unless-stopped
    ports:
      - "8192:8192"
    volumes:
      - /docker-data/app-release-watcher/data:/data
