services:
  watcher:
    build:
      context: https://github.com/RajnishOne/AppReleaseWatcher.git#main
      dockerfile: Dockerfile
    container_name: app-release-watcher
    restart: unless-stopped
    ports:
      - "8192:8192"
    volumes:
      - /docker-data/app-release-watcher/data:/data
