services:
  app-watch:
    image: rajnishdock/app-watch:latest
    container_name: app-watch
    restart: unless-stopped
    ports:
      - "8192:8192"
    volumes:
      - /docker-data/app-watch/data:/data
